### PR TITLE
Add Customer Portal Integration

### PR DESCRIPTION
**Pull request by cjavilla-stripe**
cc @tmarek-stripe @jrondeau-stripe @dawn-stripe 

This PR adds support for a customer portal integration as part of this sample. I don't think we need separate samples for creating a subscription and managing them.

The big question is around where we store the ID of the customer for demonstration purposes. I'm in favor of keeping it in environment variables and we already have this expectation about price IDs. 

Curious thoughts around this in general as we'd like to write some docs for Checkout + Customer Portal and make that the default path.

### CODE REVIEW

**Comment by cjavilla-stripe** [comment]
cc @thorsten-stripe I'm not 100% confident in the vanilla php change I made here. I was running into an issue creating a new POST route that was not accepting any json, is this cool to just repurpose most of shared? or should we be separating the concerns of deserializing json and checking the last_json_error in another shared module?

**Comment by cjavilla-stripe** [comment]
This is the point in the video where I got to actually thinking about and adding the portal: https://youtu.be/PJk6cQGDovg?t=9871

**Comment by tmarek-stripe** [comment]
@cjavilla-stripe 
> The big question is around where we store the ID of the customer for demonstration purposes. I'm in favor of keeping it in environment variables and we already have this expectation about price IDs.

Given that we're following the same pattern for Price IDs in other samples, I think it makes sense to store the Customer ID as an environment variable for the sake of consistency. That being said, it could be a bit confusing since there's really no need to store anything but the API keys as an environment variable, and it isn't something you'd ever do in production. The only other alternative I can think of is to have a constants file where you define these and have a comment at the top explaining that these constants would normally be stored in a database of some kind.

**Comment by cjavilla-stripe** [comment]
Thanks for those thoughts @tmarek-stripe. Another alternative we could consider is some sort of ephemeral user that we create? Imagine a "register" button that would create a customer and store it's ID in the sesison / cookies or similar and we would consider that the authenticated user. Then we use their ID moving forward. It would show the step for creating the customer which would be a little closer to the recommendation: create the customer when a user first signs up for your service.

It could be a stand alone page with just one button "register" and that would make a POST to the server to create a customer and redirect to the plan selection page.

**Comment by jrondeau-stripe** [comment]
I love the ephemeral user idea @cjavilla-stripe -- exactly what you say, gets us closer to the complete recommended workflow. Which means it's easier (or at least cleaner/clearer) to document :-)

**Pull request merged**
